# Generated by Django 2.2 on 2019-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='info_URL',
            field=models.URLField(blank=True),
        ),
    ]
