# Generated by Django 2.2 on 2019-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_calendar', '0004_blogpost_slice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='youtube_URL',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
