# Generated by Django 2.2 on 2019-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_calendar', '0005_blogpost_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_lesson',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
