# Generated by Django 2.2 on 2019-11-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_calendar', '0006_blogpost_is_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_lesson',
            field=models.BooleanField(),
        ),
    ]
