# Generated by Django 2.2 on 2019-11-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_calendar', '0007_auto_20191106_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slice_slug',
        ),
    ]
