# Generated by Django 2.2.27 on 2024-02-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_calendar', '0009_blog_post_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',)},
        ),
    ]
